### PR TITLE
Add type declarations for typescript

### PR DESCRIPTION
**Pull request by EmmaGoodliffe**
# Intro
Hi! I think it would be great to support typescript users by adding a type declaration file.

# Why
Because there is no `@types/input` module, it would be great if `input` included its declaration file in the module itself. This is super helpful for both linters and good text editors with intellisense.

E.g. this is what it looks like in vs code:
intellisense

# What changed
I created the `index.d.ts` file and added `index.d.ts` to the `files` option in `package.json`. (I used the documentation in `README.md` to make it).

# Just a suggestion 🤷‍♀
Obviously, feel free to improve the declaration file or decide you don't want it.

Thanks 😃!

### CODE REVIEW

**Comment by EmmaGoodliffe** [comment]
I forgot that `npm` automatically added `package-lock.json` file. Should I remove it?

**Comment by gustawdaniel** [comment]
@EmmaGoodliffe why it is removed? 

How to handle problem with lacking typescript in this package?

**Comment by EmmaGoodliffe** [comment]
@gustawdaniel I closed it because it was one of the first PRs I ever made and there was no response for a long time so I assumed I'd just done something wrong. I would be happy to re-open or create an updated version if you think it's a good idea.

As a short term solution, you can copy and paste the file I submitted to `types/input/index.d.ts` in your project, making sure that your `tsconfig.json` includes something like this:
```json
{
  "compilerOptions": {
    "typeRoots": ["./types", "./node_modules/@types"]
  }
}
```

**Comment by SwapnilSoni1999** [comment]
Why this got closed ?

**Pull request closed without merging**
